[preferred]
# Use the GTK portal for most things
default=gtk

# Use the gtk portal specifically for screen sharing
org.freedesktop.impl.portal.ScreenCast=gtk
org.freedesktop.impl.portal.Screenshot=gtk
