# Media inhibit settings
monitor_media = true
ignore_remote_media = true
inhibit_apps = ["vlc", "mpv", "/steam_app_.*/", "firefox", "chrome", "brave", "chromium", "opera", "safari"]

[[plans]]
name = "default"

[[plans.steps]]
delay = 120
# Triggers during normal idle
action = "niri msg action spawn -- swaylock & niri msg action power-off-monitors"
resume = "niri msg action power-on-monitors"

[sleep]
# Triggers specifically before the system suspends/sleeps
lock_command = "niri msg action spawn -- swaylock & niri msg action power-off-monitors"
